[package]
name = "bgj24"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.14.2", features = ["dynamic_linking"]}
bevy-inspector-egui = "0.26.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
debug = false
